/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-03-14 06:56:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class summary_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 request.setAttribute("ctx", request.getContextPath()); 
      out.write("\r\n");
      out.write("<div class=\"mod_content\" style=\"margin-left: 12px;\">\r\n");
      out.write("\t<div class=\"content_main\">\r\n");
      out.write("\t\t<div class=\"title_area\" style=\"height:1000px\">\r\n");
      out.write("\t\t\t<h2 style=\"float: left;\">总览</h2>\r\n");
      out.write("\t\t\t<form>\r\n");
      out.write("\t\t\t\t<div class=\"r relative\" id=\"datePicker\" style=\"right: 20px;\">\r\n");
      out.write("\t\t\t\t\t<a class=\"time\" id=\"datePicker_a\">\r\n");
      out.write("\t\t\t\t\t<span><p>日期选择<b id=\"displayDateTip\" style=\"font-weight:normal\"> : 查询日期</b><br><font class=\"calendar\" id=\"dateValue\">2014-06-04</font></p></span></a>\r\n");
      out.write("\t\t\t\t\t<div class=\"timetxt hide panone\" id=\"datePanel\" style=\"width: 278px; left: 0px; display: none;\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"dateBanner\" class=\"timetop\"> \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"TimeDef\" id=\"timeInputRoom\">\r\n");
      out.write("\t\t\t\t\t\t\t自定<input type=\"text\" id=\"startTime\" name=\"startTime\" class=\"Timeinput\">到 <input type=\"text\" id=\"endTime\" name=\"endTime\" class=\"Timeinput mrnone\">\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"opeDiv after\">\r\n");
      out.write("\t\t\t\t\t\t\t<small id=\"datamessage\" style=\"display: none; margin-left: 30px;\" class=\"l\"></small>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"timecolse r Confirm\" id=\"confirmBtn\">确定</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"r Cancel\" id=\"cancelBtn\">取消</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function updateAll(){\r\n");
      out.write("\tblockAll();\r\n");
      out.write("}\r\n");
      out.write("function blockAll(){\r\n");
      out.write("\t$(\"#divGaiKuang\").block({message:\"<image src='images/WaitProcess.gif'>\",css:{border:'none',backgroundColor:'transparent'},overlayCSS:{opacity:0}});\r\n");
      out.write("\t$(\"#divHuoYue\").block({message:\"<image src='images/WaitProcess.gif'>\",css:{border:'none',backgroundColor:'transparent'},overlayCSS:{opacity:0}});\r\n");
      out.write("\t$(\"#divChongZhi\").block({message:\"<image src='images/WaitProcess.gif'>\",css:{border:'none',backgroundColor:'transparent'},overlayCSS:{opacity:0}});\r\n");
      out.write("\t$(\"#divXiaoFei\").block({message:\"<image src='images/WaitProcess.gif'>\",css:{border:'none',backgroundColor:'transparent'},overlayCSS:{opacity:0}});\r\n");
      out.write("\t$(\"#divZhuanHuaLv\").block({message:\"<image src='images/WaitProcess.gif'>\",css:{border:'none',backgroundColor:'transparent'},overlayCSS:{opacity:0}});\r\n");
      out.write("\t$(\"#divLiuCun\").block({message:\"<image src='images/WaitProcess.gif'>\",css:{border:'none',backgroundColor:'transparent'},overlayCSS:{opacity:0}});\r\n");
      out.write("\t$(\"#divZuanChart\").block({message:\"<image src='images/WaitProcess.gif'>\",css:{border:'none',backgroundColor:'transparent'},overlayCSS:{opacity:0}});\r\n");
      out.write("\t$(\"#divShopChart\").block({message:\"<image src='images/WaitProcess.gif'>\",css:{border:'none',backgroundColor:'transparent'},overlayCSS:{opacity:0}});\r\n");
      out.write("\t$(\"#divShouRuChart\").block({message:\"<image src='images/WaitProcess.gif'>\",css:{border:'none',backgroundColor:'transparent'},overlayCSS:{opacity:0}});\r\n");
      out.write("\t$(\"#divShiShiChart\").block({message:\"<image src='images/WaitProcess.gif'>\",css:{border:'none',backgroundColor:'transparent'},overlayCSS:{opacity:0}});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function _lessStartDay(day){\r\n");
      out.write("\tvar end = $(\"#startTime\").val();\r\n");
      out.write("\tend = new Date(end);\r\n");
      out.write("\tend.setDate(end.getDate() - day);\r\n");
      out.write("\treturn end.Format(\"yyyy-MM-dd\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(function () {\r\n");
      out.write("\tinitDatePicker({func:updateAll,days:1,noEnd:true},'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serverTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${timezonerawoffset}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\r\n");
      out.write("\tupdateAll();\r\n");
      out.write("\t$(\".content_main\").css(\"overflow\",\"scroll\");\r\n");
      out.write("});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
