/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-03-14 07:19:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.pss.redeem;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/pss/redeem/../../mutiselectarea.jsp", Long.valueOf(1489471945372L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
request.setAttribute("ctx", request.getContextPath());
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/css.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/game/item.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\n");
      out.write("<!--\r\n");
      out.write(".file{ filter:alpha(opacity:0);opacity: 0;}\r\n");
      out.write(".record_title{background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/manage_center/keys.png);}\r\n");
      out.write(".datagrid-row{\r\n");
      out.write("    height: 25px;\r\n");
      out.write("}\r\n");
      out.write(".datagrid-cell,\r\n");
      out.write(".datagrid-cell-group,\r\n");
      out.write(".datagrid-header-rownumber,\r\n");
      out.write(".datagrid-cell-rownumber {\r\n");
      out.write("   font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("-->\n");
      out.write("</style>\r\n");
      out.write("<div class=\"title_area\">\r\n");
      out.write("\t<h2>玩家补偿</h2>\r\n");
      out.write("</div>\r\n");
      out.write("<input id=\"ctx\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("<div class=\"bd\" style=\"padding-top: 10px;margin-bottom: 10px;\">\r\n");
      out.write("     <div id=\"tabs\" class=\"easyui-tabs\" style=\"height: auto;\">\r\n");
      out.write("\t\t<div title=\"补偿\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div title=\"历史记录\">\r\n");
      out.write("\t\t   <div style=\"width: 100%; display: inline-block;\">\r\n");
      out.write("\t\t      <div class=\"record_title\">\r\n");
      out.write("\t\t             您好，你所有的操作将会被记录！\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"Container\"></div>\r\n");
      out.write("<div id=\"mask_div\" class=\"ui_mask\" style=\"width: 1920px; height: 1746px; position: absolute; top: 0px; left: 0px; display: none; background-color: rgb(0, 0, 0); opacity: 0.6; z-index: 999; background-position: initial initial; background-repeat: initial initial;\"></div>\r\n");
      out.write("<div id=\"batch_players\" class=\"pop_layer_v2\" style=\"display:none;\">\r\n");
      out.write("    <div class=\"pop_layer_main to_redeem_div\" style=\"border: none;\">\r\n");
      out.write("        <div class=\"pop_layer_title\">\r\n");
      out.write("\t\t   <h3>上传角色\r\n");
      out.write("\t\t   <span id=\"batch_players_pop_error\" class=\"tip_error\"></span>\r\n");
      out.write("\t\t   </h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t <div class=\"pop_layer_cont\">\r\n");
      out.write("\t\t    <div><p>文件格式支持纯文本， 格式为每行：   userid&nbsp;&nbsp;&nbsp;&nbsp;rolename</p></div>\r\n");
      out.write("\t\t    <div>\r\n");
      out.write("\t\t       <span id=\"progress\" class=\"progress-bar\" style=\"background-color: #00FF00;\"></span>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    <div class=\"file-box\">\r\n");
      out.write("\t\t     <span class=\"tip\">文件：</span>\r\n");
      out.write("\t\t     <input id=\"upfileDisplay\" class=\"inputlength\" readonly=\"readonly\"/>\r\n");
      out.write("\t\t     <input type='button' id=\"batch_scan\" class='btn btn_blue' value='浏览...' />\r\n");
      out.write("\t\t     <input type=\"file\" id=\"batch_players_upload\" name=\"players\" class=\"file\"/>\r\n");
      out.write("\t\t     <input type=\"submit\" id=\"uploadsubmit\" name=\"submit\" style=\"margin-left: 10px;\" class=\"btn btn_blue\" value=\"上传\" />\r\n");
      out.write("\t\t     <button class=\"btn btn_blue\" onclick=\"$('#batch_players').hide()\">取消</button>\r\n");
      out.write("\t\t     </div>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"formDiv\" style=\"display:none;\" class=\"pop_layer_v2 to_redeem_div\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
request.setAttribute("ctx", request.getContextPath());
      out.write("\r\n");
      out.write("<!-- 要实现多选服的页面要include这个页面 -->\r\n");
      out.write("<div id=\"mulSelectAreaDiv\" style=\"display:none;\" class=\"pop_layer_v2\">\r\n");
      out.write("    <input class=\"ghostStore\" type=\"hidden\"/>\r\n");
      out.write("    <input class=\"virginSet\" type=\"hidden\"/>\r\n");
      out.write("    <input class=\"defaultSelectFlag\" type=\"hidden\"/>\r\n");
      out.write("    <div class=\"pop_layer_main\">\r\n");
      out.write("\t\t<div class=\"pop_layer_title\">\r\n");
      out.write("  \t\t  <h3>选服管理\r\n");
      out.write("           <span id=\"pop_error\" class=\"tip_error\"></span>\r\n");
      out.write("          </h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"pop_layer_cont\">\r\n");
      out.write("        \t<input type=\"checkbox\" class=\"btn_select_16\" onchange=\"allSelectOrNot(this)\"/>当前页全选\r\n");
      out.write("        \t<input type=\"checkbox\" class=\"btn_select_16 allAreaOption\"/>选择所有区（选中这个所有服操作）\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"muliDisplayArea pop_layer_cont\">\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("     </div>\r\n");
      out.write("<div class=\"pop_layer_ft\"><a class=\"btn btn_submit not_close btn_blue\" href=\"javascript:multiAssure();\"><span class=\"\">确定</span></a><a class=\"btn btn_white_2 btn_close\" href=\"javascript:multiCancel();\"><span>取消</span></a></div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    //往areaCache里放入默认的选区\r\n");
      out.write("    multiAreaReset();\r\n");
      out.write("     var $displayCurArea = $('#displayCurrentArea span');\r\n");
      out.write("     var areaId = $($displayCurArea[0]).html();\r\n");
      out.write("     if(areaId && areaId.length > 0){\r\n");
      out.write("    \t var id = parseInt(areaId);\r\n");
      out.write("\t\t  areaCache[id] = id;\r\n");
      out.write("     }\r\n");
      out.write("     var worldId = $($displayCurArea[1]).html();\r\n");
      out.write("     if(worldId && worldId.length > 0){\r\n");
      out.write("    \t var id = parseInt(worldId);\r\n");
      out.write("    \t worldCache[id] = id;\r\n");
      out.write("     }\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("mailCache = '';\r\n");
      out.write("batchPlayersTr = '<tr class=\"filledTr\"><td>{}</td><td>{}</td><td>{}</td></tr>';\r\n");
      out.write("\r\n");
      out.write("itemTr = '<tr class=\"filledTr\"><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>';\r\n");
      out.write("\r\n");
      out.write("commonDelete = '<a href=\\\"javascript:;\\\" onclick=\\\"removeFromTable(this)\\\">删除</a>';\r\n");
      out.write("\r\n");
      out.write("var $itemSource;\r\n");
      out.write("    $(function(){\r\n");
      out.write("    \tinitTabs();\r\n");
      out.write("    \t//itemTemplates\r\n");
      out.write("\t  \tfillItemTemplates();\r\n");
      out.write("\t  \t$itemSource = $('#item_choose_list option').clone(true);\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    function listItems(obj){\r\n");
      out.write("    \tvar value = $(obj).val();\r\n");
      out.write("    \t\r\n");
      out.write("    \t$('#item_choose_list').empty();\r\n");
      out.write("    \t\r\n");
      out.write("    \t$itemSource.each(function(){\r\n");
      out.write("    \t\tvar add = false;\r\n");
      out.write("    \t\tif(!value){\r\n");
      out.write("    \t\t\tadd = true;\r\n");
      out.write("    \t\t}else if($(this).text().indexOf(value) != -1){\r\n");
      out.write("   \t\t\t\tadd = true;\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\tif(add){\r\n");
      out.write("    \t\t\t$(this).clone().appendTo('#item_choose_list');\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t});\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function fillItemTemplates(){\r\n");
      out.write("    \tvar itemCache = genItems;\r\n");
      out.write("    \tfor(var i = 0; i < itemCache.length; i++){\r\n");
      out.write("    \t\tvar itemTemplate = itemCache[i];\r\n");
      out.write("    \t\t$('<option value=\\\"' + itemTemplate.id + '\\\">' + itemTemplate.name + '</option>').appendTo($('#item_choose_list'));\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    //填充邮件模板选择\r\n");
      out.write("    function fillMailTemplates(){\r\n");
      out.write("    \tmailCache = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mailTemplateList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(";\r\n");
      out.write("    \tfor(var i = 0; i < mailCache.length; i++){\r\n");
      out.write("    \t\tvar mailTemplate = mailCache[i];\r\n");
      out.write("    \t\taddMailTemplateToSelect(mailTemplate, false);\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    //function showRedeemOpt(obj){\r\n");
      out.write("    //\tvar content = $(obj).html();\r\n");
      out.write("    //\tif(!content){\r\n");
      out.write("    //\t\t$(obj).load('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/pss/redeem/redeemopt.do');\r\n");
      out.write("    //\t}\r\n");
      out.write("    //}\r\n");
      out.write("    function showRedeemOpt(obj){\r\n");
      out.write("    \t$('#Container').html('');\r\n");
      out.write("    \t$('#Container').load('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/pss/redeem/redeemopt.do');\r\n");
      out.write("    }\r\n");
      out.write("    function showSendMail(obj){\r\n");
      out.write("    \t$('#Container').html('');\r\n");
      out.write("    \t$('#Container').load('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/pss/redeem/sendMail.do');\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function showRedeemRecord(obj){\r\n");
      out.write("    \t$('#Container').html('');\r\n");
      out.write("    \t$('#Container').load('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/pss/redeem/redeemrecord.do');\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function redeemmailrecord(obj){\r\n");
      out.write("    \t$('#Container').html('');\r\n");
      out.write("    \t$('#Container').load('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/pss/redeem/redeemmailrecord.do');\r\n");
      out.write("    }\r\n");
      out.write("    function initTabs(){\r\n");
      out.write("    \t$(\"#tabs\").tabs({\r\n");
      out.write("    \t\tborder:true,\r\n");
      out.write("    \t\ttabWidth:200,\r\n");
      out.write("    \t\ttabHeight:40,\r\n");
      out.write("    \t\tonSelect:function(title){\r\n");
      out.write("    \t\t\tvar selectTabPanel = $('#tabs').tabs('getSelected'); \r\n");
      out.write("\t\t\t\tif('补偿' == title){\r\n");
      out.write("\t\t\t\t\tshowRedeemOpt(selectTabPanel[0]);\r\n");
      out.write("\t\t\t\t}else if('历史记录'== title){\r\n");
      out.write("\t\t\t\t\tshowRedeemRecord(selectTabPanel[0]);\r\n");
      out.write("\t\t\t\t}else if('邮件'== title){\r\n");
      out.write("\t\t\t\t\tshowSendMail(selectTabPanel[0]);\r\n");
      out.write("\t\t\t\t}else if('邮件历史记录'==title){\r\n");
      out.write("\t\t\t\t\tredeemmailrecord(selectTabPanel[0]);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\t});\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    //redeemCommit 等函数挪到了baofeng.js\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
