/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-03-14 07:19:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.pss.redeem;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class redeemopt_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
request.setAttribute("ctx", request.getContextPath());
      out.write("\r\n");
      out.write("<div id=\"content_area\" style=\"overflow: auto; vertical-align: top;height:700px;\">\r\n");
      out.write("      <div class=\"to_redeem_div\" style=\"width: 53%; display: inline-block;\">\r\n");
      out.write("         <div><h3><span id=\"mail_pop_error\" class=\"tip_error\"></span></h3></div>\r\n");
      out.write("         <div>\r\n");
      out.write("           <span class=\"tip\">标题：</span><input id=\"mailtitle\" name=\"mailtitle\" class=\"inputlength\"/>\r\n");
      out.write("  <span class=\"tip\">选择邮件模板：</span><select id=\"mail_select_title\" class=\"inputlength mail_select_title\" ><option value=\"-1\">无</select>\r\n");
      out.write("        <button class=\"btn btn_blue\" onclick=\"modifyMailTemplate()\">修改</button>\r\n");
      out.write("        <button class=\"btn btn_blue\" onclick=\"addMailTemplate()\">增加</button>\r\n");
      out.write("  <button class=\"btn btn_blue\" onclick=\"deleteMailTemplate()\">删除</button>\r\n");
      out.write("  <button class=\"btn btn_blue\" onclick=\"toSelMultiArea(1, '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("')\">选服</button>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("   <span class=\"tip\" style=\"vertical-align: top;\">内容：</span><textarea id=\"mailcontent\" name=\"mailcontent\" rows=\"10\" cols=\"110\" style=\"width: auto;\"></textarea>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("   <span class=\"tip\">角色类型：</span>\r\n");
      out.write("   <select name=\"role_type\" class=\"inputlength\">\r\n");
      out.write("     \t\t    <option value=\"0\">部分玩家</option>\r\n");
      out.write("     \t\t    <option value=\"1\">所有玩家</option>\r\n");
      out.write("     <!-- \t\t    <option value=\"2\">所有新玩家</option> -->\r\n");
      out.write("     \t\t</select>\r\n");
      out.write("     \t\t<button id=\"to_batch_add\" class=\"btn btn_blue\" onclick=\"popUp('batch_players');\">批量</button>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("    <span class=\"tip\" style=\"margin-left: 2px;\">帐号：</span>\r\n");
      out.write("    <input id=\"role_id\" name=\"role_id\" class=\"inputlength\"/>\r\n");
      out.write("    <button class=\"btn btn_blue\" title=\"添加角色\" onclick=\"addRoleToTable()\">添加</button>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("    <span class=\"tip\" style=\"margin-left: 2px;\">角色名：</span>\r\n");
      out.write("    <input id=\"role_name\" name=\"role_name\" class=\"inputlength\"/>\r\n");
      out.write("    <span class=\"tip\" style=\"margin-left: 2px;\">钻石：</span>\r\n");
      out.write("    <input id=\"redeem_diamond\" name=\"redeem_diamond\" class=\"intonly\"/>(注：钻石小于等于0，就是发邮件)\r\n");
      out.write("    <span id=\"role_error\" class=\"tip_error\"></span>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("   <!-- 角色表格 -->\r\n");
      out.write("   <div style=\"display:inline-block;float:left;\">\r\n");
      out.write("     <table id=\"role_display_head_table\" class=\"displaying\">\r\n");
      out.write("        <thead>\r\n");
      out.write("        <tr class=\"title\"><th>帐号</th><th>角色名</th><th style=\"border-right: none;\">操作</th><th style=\"width:10px;border-left: none;\"></th></tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("     </table>\r\n");
      out.write("     <div class=\"display_body_div\">\r\n");
      out.write("     <table id=\"role_display_body_table\" class=\"displaying\">\r\n");
      out.write("       <thead>\r\n");
      out.write("        <tr class=\"title\"><th>帐号</th><th>角色名</th><th>操作</th></tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("        <tr><td></td><td></td><td></td></tr>\r\n");
      out.write("        <tr><td></td><td></td><td></td></tr>\r\n");
      out.write("        <tr><td></td><td></td><td></td></tr>\r\n");
      out.write("        <tr><td></td><td></td><td></td></tr>\r\n");
      out.write("        <tr><td></td><td></td><td></td></tr>\r\n");
      out.write("        <tr><td></td><td></td><td></td></tr>\r\n");
      out.write("        <tr><td></td><td></td><td></td></tr>\r\n");
      out.write("        </tbody>\r\n");
      out.write("     </table>\r\n");
      out.write("     </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("<input type=\"hidden\" id=\"redeem_type\" value=\"\" />\r\n");
      out.write("      </div>\r\n");
      out.write("<input type=\"hidden\" id = \"multiResultPlace\" value=\"0\"/>\r\n");
      out.write(" <div style=\"padding-left: 20px;\">\r\n");
      out.write("    <button id=\"redeem_commit\" class=\"btn btn_blue\" onclick=\"redeemCommit()\">提交</button>\r\n");
      out.write("    <button id=\"redeem_reset\" class=\"btn btn_blue\" onclick=\"redeemReset()\">重置</button>\r\n");
      out.write("</div>\r\n");
      out.write("  </div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   $(function(){\r\n");
      out.write("\t   calScrollTableWidth('role_display_head_table', 'role_display_body_table');\r\n");
      out.write("\t  \tcalScrollTableWidth('item_display_head_table', 'item_display_body_table');\r\n");
      out.write("\t  \t\r\n");
      out.write("\t  \tfillMailTemplates();\r\n");
      out.write("\t  \t$('#mail_select_title').change(function(){\r\n");
      out.write("\t  \t\tmailSelectChange();\r\n");
      out.write("\t  \t});\r\n");
      out.write("\t  \t\r\n");
      out.write("\t  \t$('#batch_players_upload').change(function(){\r\n");
      out.write("\t  \t\t$('#upfileDisplay').attr('value', $(this).val());\r\n");
      out.write("\t  \t});\r\n");
      out.write("\t  \t\r\n");
      out.write("\t  \tbatchPendingPlayersUpload();\r\n");
      out.write("\t  \t\r\n");
      out.write("\t  \t$('#selected_itemid').keyup(function(){\r\n");
      out.write("\t  \t\tselectItemIdKeyup();\r\n");
      out.write("\t  \t});\r\n");
      out.write("\t  \t\r\n");
      out.write("\t  \tonlyInputInt();\r\n");
      out.write("   });\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
