/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-03-14 07:19:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.ps.area;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class gamelist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/ps/area/hiddenStatus.jsp", Long.valueOf(1489471945378L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005ftext_005fcode_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005ftext_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005ftext_005fcode_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
request.setAttribute("ctx", request.getContextPath());
      out.write("\r\n");
      out.write("<style type=\"text/css\">\n");
      out.write("<!--\n");
      out.write(".btn_white_2 {\r\n");
      out.write("border: 1px solid #c0c4cd;\r\n");
      out.write("border-radius: 3px;\r\n");
      out.write("background: #fff;\r\n");
      out.write("color: #0071ce;\r\n");
      out.write("}\r\n");
      out.write(".mod_select_down a:hover{\r\n");
      out.write("    background-color: #e2e2e2;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("<div class=\"title_area\">\r\n");
      out.write("\t<h2>游戏服管理</h2>\r\n");
      out.write("</div>\r\n");
      out.write("<input type=\"hidden\" id=\"ctx\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("<div class=\"bd\" style=\"padding-top: 10px;\">\r\n");
      out.write("    <div class=\"search\">\r\n");
      out.write("        <div class=\"mod_select_down\" style=\"display: inline-block; vertical-align: top;\">\r\n");
      out.write("             <a href=\"javascript:void(0);\" onclick=\"return false;\" id=\"search_type_btn\" class=\"btn_white_2 btn_select_outline\" value=\"0\"><span>服务器ID</span><i class=\"ico\"></i></a>\r\n");
      out.write("             <ul class=\"down_list btn_select_outline\" id=\"search_type_list\" style=\"display: none;\">\r\n");
      out.write("                 <li><a href=\"javascript:void(0);\" onclick=\"return false;\" class=\"exclude\" value=\"0\" targetPlaceholder=\"请输服务器ID\">服务器ID</a></li>\r\n");
      out.write("                 <li><a href=\"javascript:void(0);\" onclick=\"return false;\" class=\"exclude\" value=\"1\" targetPlaceholder=\"请输服务器IP\">服务器IP</a></li>\r\n");
      out.write("                 <li><a href=\"javascript:void(0);\" onclick=\"return false;\" class=\"exclude\" value=\"2\" targetPlaceholder=\"游戏区ID\">游戏区ID</a></li>\r\n");
      out.write("             </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"display: inline-block;\">\r\n");
      out.write("\t        <span class=\"text_area\"><textarea id=\"ipsearchinput\" style=\"color:#333;\" placeholder=\"请输服务器ID\"></textarea></span> \r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"searchbutton\"></button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"display: inline-block; vertical-align: top;\">\r\n");
      out.write("\t\t\t<!-- <button class=\"btn btn_blue\" onclick=\"exportExcel()\" style=\"margin-top:0px;\">导出Excel</button> -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<div class=\"bd_title\">\r\n");
      out.write("\t\t<div class=\"bd_title_btns\">\r\n");
      out.write("\t\t\t<a id=\"btn_rename\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" style=\"display: none;\" class=\"btn btn_blue\" title=\"增加一个实例\"><span>新增</span></a>\r\n");
      out.write("\t\t\t<a id=\"btn_back\" href=\"javascript:void(0);\" style=\"display: none;\" onclick=\"return false;\" class=\"btn btn_disable_v2\" title=\"请选择一个或多个实例\"><span>退还</span></a>\r\n");
      out.write("\t\t\t<a id=\"btn_project\" href=\"javascript:void(0);\" onclick=\"return false;\" class=\"btn btn_disable_v2\" title=\"请选择一个或多个实例\" style=\"display: none;\"><span>分配至项目</span></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"bd_title_op\">\r\n");
      out.write("\t\t\t<a id=\"btn_refresh\" href=\"javascript:void(0);\" onclick=\"return false;\" class=\"ico ico_refresh\" title=\"刷新当前页面\"><span class=\"visually_hidden\">刷新</span></a>\r\n");
      out.write("\t\t\t<a id=\"btn_setting\" href=\"javascript:void(0);\" onclick=\"return false;\" class=\"ico ico_setting\" title=\"设置列表显示字段\"><span class=\"visually_hidden\">设置</span></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("                            \r\n");
      out.write("\t<div class=\"table_area\" style=\"overflow: auto;\">\r\n");
      out.write("\t\t<div class=\"table_mask\" id=\"cont_table_area\" style=\"width: 100%;\">\r\n");
      out.write("\t\t  ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"hideStatusDiv\" style=\"display:none;\">\r\n");
      out.write("   <div class=\"image_0\">\r\n");
      out.write("        <img alt=\"\" style=\"vertical-align: middle;margin-right:10px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/manage_center/running.jpg\">");
      if (_jspx_meth_spring_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"image_1\">\r\n");
      out.write("        <img alt=\"\" style=\"vertical-align: middle;margin-right:10px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/manage_center/maintain.jpg\">");
      if (_jspx_meth_spring_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"image_2\">\r\n");
      out.write("        <img alt=\"\" style=\"vertical-align: middle;margin-right:10px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/manage_center/stop.jpg\">");
      if (_jspx_meth_spring_005fmessage_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"mask_div\" class=\"ui_mask\" style=\"width: 1920px; height: 1746px; position: absolute; top: 0px; left: 0px; display: none; background-color: rgb(0, 0, 0); opacity: 0.6; z-index: 999; background-position: initial initial; background-repeat: initial initial;\"></div>\r\n");
      out.write("<div id=\"formDiv\" style=\"display:none;\" class=\"pop_layer_v2\">\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\t// AJAX去加载页面, 显示加载图片，加载目标页面，隐藏加载图片\r\n");
      out.write("\tajaxALink('#formDiv');\r\n");
      out.write("\tcommonServerPagination('#areaListTable', undefined, \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ps/area/arealist.do\", {'editorField':['openTime', 'combineTime'], 'searchvalue':function(){\r\n");
      out.write("\t\treturn $('#ipsearchinput').val();\r\n");
      out.write("\t}, 'searchtype': function(){\r\n");
      out.write("\t\treturn $('#search_type_btn').attr('value');\r\n");
      out.write("\t}});\r\n");
      out.write("\t$('.searchbutton').click(function(){\r\n");
      out.write("\t\t$('#areaListTable').datagrid('reload');\r\n");
      out.write("\t});\r\n");
      out.write("\tselectListInit({listChoose: function($lia){\r\n");
      out.write("\t\t$lia.closest('.mod_select_down').next().find('textarea').attr('placeholder', $lia.attr('targetPlaceholder'));\r\n");
      out.write("\t}});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#ipsearchinput').bind('keypress',function(event){\r\n");
      out.write("\t\tif(event.keyCode == \"13\"){\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t$('.searchbutton').click();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function dateSaveCallback(obj, choice){\r\n");
      out.write("\tvar $idObj = $(obj).closest('td[field=openTime]').parent().find('td[field=worldId]');\r\n");
      out.write("\tvar worldId = $idObj.text();\r\n");
      out.write("\tif(choice == 1){ //save\r\n");
      out.write("\t\tvar input = $(obj).parent().find('input').val();\r\n");
      out.write("\t    if(!input){\r\n");
      out.write("\t    \talert(\"时间不能为空\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    var data = $('#areaListTable').datagrid('getData');\r\n");
      out.write("\t    var rows;\r\n");
      out.write("\t\tfor(var i = 0; i < data.rows.length; i++){\r\n");
      out.write("\t\t\tif(data.rows[i].worldId == worldId){\r\n");
      out.write("\t\t\t\tvar oldTime = data.rows[i].openTime;\r\n");
      out.write("\t\t\t\tif(oldTime == input){\r\n");
      out.write("\t\t\t\t\talert(\"时间没有修改\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\trows = data.rows[i];\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t$.post('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ps/area/modifyopentime.do', {worldId:worldId, openTime:input}, function(data){\r\n");
      out.write("\t\t\t\tif(data.key == 0){\r\n");
      out.write("\t\t\t\t\t$('#areaListTable').datagrid('cancelEdit', i);\r\n");
      out.write("\t\t\t\t\talert('修改失败');\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$('#areaListTable').datagrid('endEdit', i);\r\n");
      out.write("\t\t\t\t\trows.openTime = data.value;\r\n");
      out.write("\t\t\t\t\t$('#areaListTable').datagrid('reload');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tvar data = $('#areaListTable').datagrid('getData');\r\n");
      out.write("\t\tfor(var i = 0; i < data.rows.length; i++){\r\n");
      out.write("\t\t\tif(data.rows[i].worldId == worldId){\r\n");
      out.write("\t\t\t\t$('#areaListTable').datagrid('cancelEdit', i);\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function dateSaveCallback2(obj, choice){\r\n");
      out.write("\tvar $idObj = $(obj).closest('td[field=combineTime]').parent().find('td[field=worldId]');\r\n");
      out.write("\tvar worldId = $idObj.text();\r\n");
      out.write("\tif(choice == 1){ //save\r\n");
      out.write("\t\tvar input = $(obj).parent().find('input').val();\r\n");
      out.write("\t    if(!input){\r\n");
      out.write("\t    \talert(\"时间不能为空\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    var data = $('#areaListTable').datagrid('getData');\r\n");
      out.write("\t    var rows;\r\n");
      out.write("\t\tfor(var i = 0; i < data.rows.length; i++){\r\n");
      out.write("\t\t\tif(data.rows[i].worldId == worldId){\r\n");
      out.write("\t\t\t\tvar oldTime = data.rows[i].combineTime;\r\n");
      out.write("\t\t\t\tif(oldTime == input){\r\n");
      out.write("\t\t\t\t\talert(\"时间没有修改\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\trows = data.rows[i];\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.post('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ps/area/modifycombinetime.do', {worldId:worldId, combineTime:input}, function(data){\r\n");
      out.write("\t\t\t\tif(data.key == 0){\r\n");
      out.write("\t\t\t\t\t$('#areaListTable').datagrid('cancelEdit', i);\r\n");
      out.write("\t\t\t\t\talert('修改失败');\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$('#areaListTable').datagrid('endEdit', i);\r\n");
      out.write("\t\t\t\t\trows.combineTime = data.value;\r\n");
      out.write("\t\t\t\t\t$('#areaListTable').datagrid('reload');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tvar data = $('#areaListTable').datagrid('getData');\r\n");
      out.write("\t\tfor(var i = 0; i < data.rows.length; i++){\r\n");
      out.write("\t\t\tif(data.rows[i].worldId == worldId){\r\n");
      out.write("\t\t\t\t$('#areaListTable').datagrid('cancelEdit', i);\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function openTimeFormatter(value,row,index){\r\n");
      out.write("\tif(value && value.length == 'yyyy-MM-dd hh:mm:ss'.length + 2){\r\n");
      out.write("\t\tvar ret = value.substr(0, value.length - 2);\r\n");
      out.write("\t\treturn ret;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn value;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function toShow(){\r\n");
      out.write("\t  $('#mask_div').show();\r\n");
      out.write("\t  $('#formDiv').css(\"position\", \"absolute\");\r\n");
      out.write("\t  var left = ($('.content_main').width() - $('#formDiv').width()) / 2;\r\n");
      out.write("\t  $('#formDiv').css(\"left\", left);\r\n");
      out.write("\t  $('#formDiv').show();\r\n");
      out.write("\t  $('#formDiv').draggable({handle:'.pop_layer_title'});\r\n");
      out.write(" }\r\n");
      out.write(" function cancel(){\r\n");
      out.write("\t  $('#mask_div').hide();\r\n");
      out.write("\t  $('#formDiv').hide();\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" function popSubmit(){\r\n");
      out.write("\t var action = $(\"#postform\").attr(\"action\");\r\n");
      out.write("\t \r\n");
      out.write("\t $.ajax({\r\n");
      out.write("         cache: true,\r\n");
      out.write("         type: \"POST\",\r\n");
      out.write("         url:action,\r\n");
      out.write("         data:$('#postform').serialize(),// 你的formid\r\n");
      out.write("         async: false,\r\n");
      out.write("         error: function(request, errorMsg) {\r\n");
      out.write("             $('#pop_error').html(errorMsg);\r\n");
      out.write("         },\r\n");
      out.write("         success: function(data) {\r\n");
      out.write("             $('.content_main').html(data);\r\n");
      out.write("         }\r\n");
      out.write("     });\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" function exportExcel(){\r\n");
      out.write("\t\twindow.open('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ps/area/export.do');\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/jsp/ps/area/gamelist.jsp(43,28) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/ps/area/create.do");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t    ");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /WEB-INF/jsp/ps/area/gamelist.jsp(56,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ areaListSize le 0}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t  <div class=\"table_blank\">\r\n");
        out.write("\t\t\t\t<p class=\"text\">还没有区服</p>\r\n");
        out.write("\t\t      </div>\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t<div>\r\n");
        out.write("\t\t\t\t    <input type=\"hidden\" class=\"hiddenEditingIndex\"/>\r\n");
        out.write("\t\t\t\t\t<table id=\"areaListTable\" style=\"height: 640px;\">\r\n");
        out.write("\t\t\t\t\t<thead style=\"height: 31px\">\r\n");
        out.write("\t\t\t\t\t\t<tr>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-options=\"field:'worldId',width:calColumnWidth(0.05)\" title=\"研发商分配的世界ID\">官方ID</th>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-options=\"field:'worldName',width:calColumnWidth(0.05)\" title=\"研发商分配的名称\">服务器名</th>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-options=\"field:'followerId',width:calColumnWidth(0.05)\" title=\"主机leader的ID\">主机</th>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-options=\"field:'platformName',width:calColumnWidth(0.05)\" title=\"主机leader的ID\">平台</th>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-options=\"field:'areaId',width:calColumnWidth(0.05)\" title=\"平台分配的ID\">游戏区ID</th>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-options=\"field:'areaName',width:calColumnWidth(0.08)\" title=\"平台分配的ID\">游戏区名</th>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-options=\"field:'adminAddress',width:calColumnWidth(0.1)\">后台地址</th>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-options=\"field:'gameAddress',width:calColumnWidth(0.18)\">游戏地址</th>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-options=\"field:'openTime',width:calColumnWidth(0.12),\r\n");
        out.write("\t\t\t\t\t\t\t     editor:{\r\n");
        out.write("\t\t\t                           type:'bfDateEdit',\r\n");
        out.write("\t\t\t                           options:{\r\n");
        out.write("\t\t\t                               savecallback:'dateSaveCallback',\r\n");
        out.write("\t\t\t                           }\r\n");
        out.write("\t\t\t                       }\r\n");
        out.write("\t\t\t\t\t\t\t\">开服时间</th>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-options=\"field:'combineTime',width:calColumnWidth(0.12),\r\n");
        out.write("\t\t\t\t\t\t\t     editor:{\r\n");
        out.write("\t\t\t                           type:'bfDateEdit',\r\n");
        out.write("\t\t\t                           options:{\r\n");
        out.write("\t\t\t                               savecallback:'dateSaveCallback2',\r\n");
        out.write("\t\t\t                           }\r\n");
        out.write("\t\t\t                       }\r\n");
        out.write("\t\t\t\t\t\t\t\">合服时间</th>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-options=\"field:'restartTime',width:calColumnWidth(0.12)\">起服时间</th>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-options=\"field:'status',width:calColumnWidth(0.05),\r\n");
        out.write("\t\t\t\t\t\t\tformatter:function(value,row,index){\r\n");
        out.write("\t\t\t\t\t\t\t    return $('#hideStatusDiv .image_' + value).html();\r\n");
        out.write("\t\t\t\t\t\t\t}\">运行</th>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-options=\"field:'configFile',width:calColumnWidth(0.04), formatter:function(value,row,index){\r\n");
        out.write("\t\t\t\t\t\t\t    return '<a href=javascript:; onclick=downloadConfig(' + 1 + ',' + row.worldId + ')>下载</a>';\r\n");
        out.write("\t\t\t\t\t\t\t}\">配置</th>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-options=\"field:'version',width:calColumnWidth(0.18), formatter:function(value,row,index){\r\n");
        out.write("\t\t\t\t\t\t\t    var ret = '';\r\n");
        out.write("\t\t\t\t\t\t\t    var serverVersion = row['serverVersion'];\r\n");
        out.write("\t\t\t\t\t\t\t    var dataVersion = row['dataVersion'];\r\n");
        out.write("\t\t\t\t\t\t\t    if(serverVersion){\r\n");
        out.write("\t\t\t\t\t\t\t        ret += '服务器: ' + serverVersion;\r\n");
        out.write("\t\t\t\t\t\t\t        if(dataVersion){\r\n");
        out.write("\t\t\t\t\t\t\t            ret += '<br/>';\r\n");
        out.write("\t\t\t\t\t\t\t        }\r\n");
        out.write("\t\t\t\t\t\t\t    }\r\n");
        out.write("\t\t\t\t\t\t\t    if(dataVersion){\r\n");
        out.write("\t\t\t\t\t\t\t         ret += '策划数据: ' + dataVersion;\r\n");
        out.write("\t\t\t\t\t\t\t    }\r\n");
        out.write("\t\t\t\t\t\t\t    return ret;\r\n");
        out.write("\t\t\t\t\t\t\t}\">版本</th>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-options=\"field:'serverVersion',hidden:true\"></th>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-options=\"field:'dataVersion',hidden:true\"></th>\r\n");
        out.write("\t\t\t\t\t\t\t<!-- <th style=\"width:210px;\"><div class=\"op\"><span class=\"table_title\">操作</span></div></th> -->\r\n");
        out.write("\t\t\t\t\t\t</tr>\r\n");
        out.write("\t\t\t\t\t</thead>\r\n");
        out.write("\t\t\t\t\t\t<tbody>\r\n");
        out.write("\t\t\t\t\t\t</tbody>\r\n");
        out.write("\t\t\t\t\t</table>\r\n");
        out.write("\t\t\t\t  </div>\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f0 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005ftext_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f0.setParent(null);
    // /WEB-INF/jsp/ps/area/hiddenStatus.jsp(7,144) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f0.setCode("mm.area.running");
    // /WEB-INF/jsp/ps/area/hiddenStatus.jsp(7,144) name = text type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f0.setText("运行中");
    int[] _jspx_push_body_count_spring_005fmessage_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f0 = _jspx_th_spring_005fmessage_005f0.doStartTag();
      if (_jspx_th_spring_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f0.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005ftext_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f1 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005ftext_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f1.setParent(null);
    // /WEB-INF/jsp/ps/area/hiddenStatus.jsp(10,145) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f1.setCode("mm.area.maintain");
    // /WEB-INF/jsp/ps/area/hiddenStatus.jsp(10,145) name = text type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f1.setText("维护中");
    int[] _jspx_push_body_count_spring_005fmessage_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f1 = _jspx_th_spring_005fmessage_005f1.doStartTag();
      if (_jspx_th_spring_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f1.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005ftext_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f2 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005ftext_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f2.setParent(null);
    // /WEB-INF/jsp/ps/area/hiddenStatus.jsp(13,141) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f2.setCode("mm.area.stop");
    // /WEB-INF/jsp/ps/area/hiddenStatus.jsp(13,141) name = text type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f2.setText("停止");
    int[] _jspx_push_body_count_spring_005fmessage_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f2 = _jspx_th_spring_005fmessage_005f2.doStartTag();
      if (_jspx_th_spring_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f2.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005ftext_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f2);
    }
    return false;
  }
}
