
window.qcloud=window.qcloud||{};qcloud.cvmCommon=qcloud.cvmCommon||{};qcloud.cvmCommon={uin:$.cookie('uin'),isSingleSelect:false};qcloud.cvmCommon.init=function(){var me=this;this.contentTable=$('#cont_table_area table');this.contentTable.on('click','.btn_select_16',function(e){if($(this).hasClass('btn_selected_16')){$(this).removeClass('btn_selected_16');}else if(!$(this).hasClass('btn_disable')){if(me.isSingleSelect){$('.btn_selected_16').removeClass('btn_selected_16');}
$(this).addClass('btn_selected_16');}
if("function"==typeof me._checkOpsAvailable){me._checkOpsAvailable();}
e.stopPropagation();e.cancelBubble=true;return false;});this.contentTable.on('click','tr',function(e){$('.content_main .bd_content_table tr').removeClass('selected');$(this).addClass('selected');var _seq=$(this).attr("seq");if('a'!=e.target.tagName.toLowerCase()&&"function"==typeof me.showInfo){me.showInfo(me.cvmList[_seq]);}});$('.content_main .bd_title_table').on('click','.btn_select_16',function(){if(0<=this.className.indexOf('disable')){return;}
if($(this).hasClass('btn_selected_16')){$('.content_main .btn_select_16').removeClass('btn_selected_16');}else{$('.content_main .btn_select_16').not('.btn_disable').addClass('btn_selected_16');}
if("function"==typeof me._checkOpsAvailable){me._checkOpsAvailable();}});$('#btn_setting').click(function(){var titles=me.getRowTitle();for(var i in titles){var t=titles[i];if(t){$('#pop_title_setting .btn_select_16[v='+t+']').addClass('btn_selected_16');}}
$('#pop_title_setting').floatdiv({location:"middle",isShowCover:true,confirm_callback:function(){var titles=[];$('#pop_title_setting .btn_selected_16').each(function(){var t=$(this).attr('v');if($.inArray(t,titles)==-1){titles.push(t);}});me.setRowTitle(titles);if(me.createTable){me.createTable();}},close_callback:function(){me.floating=false;}}).show();me.floating=true;});$('#pop_title_setting .setting_list a').click(function(){var $i=$(this).find('i');if(!$i.hasClass('default')){if($i.hasClass('btn_selected_16')){$i.removeClass('btn_selected_16');}else{$i.addClass('btn_selected_16');}}});$('#btn_help').click(function(){$('.mod_help').show();});$('.mod_help .btn_op_close').click(function(){$('.mod_help').hide();});$('.mod_select_down li:last-child').addClass('last');me.resizeSrvArea(1);};qcloud.cvmCommon.getRowTitle=function(){var me=this,titles=$.cookie('cvm_tile_'+me.uin+location.pathname.split('/').reverse()[0].split('.')[0]),rowTitle=[];if(titles){rowTitle=$.parseJSON(titles);}else{rowTitle=me.defaultTitles;}
return rowTitle;};qcloud.cvmCommon.setRowTitle=function(titles){var me=this;$.cookie('cvm_tile_'+me.uin+location.pathname.split('/').reverse()[0].split('.')[0],$.toJSON(titles),{expires:365,path:'/',domain:COOKIE_DOMAIN});};qcloud.cvmCommon.getSelectedCvms=function(){var me=this;var selectedCvms=[],seqs=[];$('.content_main .bd_content_table .btn_selected_16').each(function(){var seq=$(this).closest('tr').attr('seq');if($.inArray(seq,seqs)==-1){var cvm=me.cvmList[seq];if(cvm){seqs.push(seq);selectedCvms.push(cvm);}}});return selectedCvms;};qcloud.cvmCommon._initPopBox=function($pop,cvms){var $submitBtn=$pop.find('.btn_submit');$pop.find('.btn_select_16').removeClass('btn_selected_16');$pop.find('input,textarea').removeClass('error').val('').keydown().blur().focus();$pop.find('.tip_error').hide();$pop.find('.qz_bubble').hide();$submitBtn.removeClass('btn_blue btn_blue_loading').addClass('btn_white_2');$submitBtn.find('span').removeClass('ico ico_loading_blue').text('确定');$pop.find('.tip_word').unbind().bind('click',function(){var $a=$(this).find('.btn_select_16');if($a.hasClass('btn_selected_16')){$a.removeClass('btn_selected_16');$submitBtn.removeClass('btn_blue').addClass('btn_white_2');}else{$a.addClass('btn_selected_16');$submitBtn.addClass('btn_blue').removeClass('btn_white_2');}});};qcloud.cvmCommon._popBoxErr=function($pop,res){if(res.retcode==9810){qcloud.util.showTips({type:"error",text:'操作失败，您未开通“管理云资源”权限，现在为您跳转首页'});setTimeout(function(){window.location.href=MAIN_DOMAIN;},3000);return;}else if(0<=$.inArray(res.retcode,[9814,9005,9925,9006])){var cvm=qcloud.cvmManage;$pop.closeFloatDiv();cvm.showPage(cvm.curPage);qcloud.cvmCommon._loadingData('hide');qcloud.util.showTips({type:"error",text:res.errmsg});return;}else if(res.retcode==2012){$('#pwd_vcode').addClass('error').focus();}
var errMsg=res.errmsg;if($pop.attr('id')=='pop_cvm_rename'){errMsg='批量改名失败，请稍后重试';}
var $submitBtn=$pop.find('.btn_submit');$pop.find('.tip_error').text(errMsg).show();$submitBtn.addClass('btn_blue').removeClass('btn_blue_loading').find('span').removeClass('ico ico_loading_blue').text('重试');};qcloud.cvmCommon._loadingData=function(flag){if(flag=='show'){$('.mod_table_loading').floatdiv({location:"middle",timeToLive:0}).show();}else{$('.mod_table_loading').closeFloatDiv();}};qcloud.cvmCommon.resizeSrvArea=function(sizeCode){if(0===this.contentTable.find('tr').length){sizeCode=1;}
$('#mod_monitor_frm .op_area .ico').removeClass('min_selected moderate_selected max_selected');var el=$('#mod_monitor_frm .op_area .ico').eq(sizeCode-1);if(3==sizeCode){$(el).addClass('max_selected');$('#srv_info_wrp').show();}else if(2==sizeCode){$(el).addClass('moderate_selected');$('#srv_info_wrp').show();}else{$(el).addClass('min_selected');$('#srv_info_wrp').hide();}
window.__srv_info_mode=sizeCode;$(window).resize();};qcloud.cvmCommon.autoHeight=function(){window.__srv_info_mode=window.__srv_info_mode||1;$('#mod_content_wrapper').css('height','auto');$(window).resize(function(){var totalHeight=Math.max($(window).height(),600)-$('#cont_table_area')[0].getBoundingClientRect().top-$(window).scrollTop()-59;var percent={3:0.8,2:0.55};var _p=percent[window.__srv_info_mode];if(_p){$('#cont_table_area').height(totalHeight*(1-_p));$('#srv_monitor_wrp').height(totalHeight*_p);$('#srv_info_wrp').height(totalHeight*_p-41);}else{$('#cont_table_area').height(totalHeight);$('#srv_monitor_wrp').height(0);}
$(document.body).css({'overflow-x':'hidden','overflow-y':'hidden','overflow':'hidden'});if(600>$(window).height()){$(document.body).css('overflow-y','auto');}
if(810>$(window).width()){$(document.body).css({'overflow-x':'auto','width':'810px'});}else{$(document.body).css('width','');}});qcloud.cvmCommon.resizeSrvArea(window.__srv_info_mode);};qcloud.cvmCommon.hideLeftNav=function(){$('#slide_nav').hide();$('#mod_content_wrapper').css({'margin-left':'15px'});$('#slide_nav_min').show();$('#btn_hide_left_nav').hide();$(window).resize();};qcloud.cvmCommon.showLeftNav=function(){$('#slide_nav').show();$('#mod_content_wrapper').css({'margin-left':'210px'});$('#slide_nav_min').hide();$('#btn_hide_left_nav').show();$(window).resize();};/*  |xGv00|d16d00510f9afd6e419a5f23da3f4365 */